#%RAML 1.0 NamedExample
value:
  - 
    id : 1 
    first_name : Ramakrishna
    last_name : Vajrala
    date_birth : 2015-05-23
    gender : Male
    role : Developer
  -
    id : 2
    first_name : Sirisha
    last_name : Ponnada
    date_birth : 2015-05-23
    gender : Female
    role : Developer
  -
    id : 3
    first_name : Anirudh
    last_name : Vajrala
    date_birth : 2015-05-23
    gender : Male
    role : Program Director
  -
    id : 4
    first_name : Akhilesh
    last_name : Vajrala
    date_birth : 2015-05-23
    gender : Female
    role : Program Director
    

    